import type { Session, Speaker } from "./types";

export const speakers: Speaker[] = [
  {
    id: "maya-chen",
    name: "Maya Chen",
    title: "Staff Web Engineer",
    company: "Northstar Labs",
    bio: "Maya builds resilient web platforms and teaches teams how to make performance a product feature.",
  },
  {
    id: "emre-kaya",
    name: "Emre Kaya",
    title: "Cloud Architect",
    company: "Skyline Systems",
    bio: "Emre helps engineering organizations design cloud systems that stay understandable as they scale.",
  },
  {
    id: "sofia-martins",
    name: "Sofia Martins",
    title: "Developer Advocate",
    company: "Open Circuit",
    bio: "Sofia turns complex AI and backend concepts into practical tools developers can use with confidence.",
  },
  {
    id: "jonas-berg",
    name: "Jonas Berg",
    title: "Principal Security Engineer",
    company: "ShieldWorks",
    bio: "Jonas focuses on pragmatic application security, secure defaults, and threat modeling for product teams.",
  },
  {
    id: "aisha-okafor",
    name: "Aisha Okafor",
    title: "Mobile Engineering Lead",
    company: "Loop Mobile",
    bio: "Aisha leads cross-platform mobile teams and cares deeply about thoughtful offline experiences.",
  },
  {
    id: "leo-garcia",
    name: "Leo Garcia",
    title: "Platform Engineer",
    company: "Launchpad",
    bio: "Leo works on developer platforms, delivery systems, and the feedback loops that keep teams moving.",
  },
  {
    id: "nora-patel",
    name: "Nora Patel",
    title: "Senior Backend Engineer",
    company: "Meridian",
    bio: "Nora designs event-driven services and enjoys making distributed systems easier to reason about.",
  },
  {
    id: "deniz-arslan",
    name: "Deniz Arslan",
    title: "Frontend Architect",
    company: "Pixel Foundry",
    bio: "Deniz creates accessible design systems that help teams ship consistent, high-quality interfaces.",
  },
  {
    id: "hugo-lee",
    name: "Hugo Lee",
    title: "ML Platform Lead",
    company: "Signal Works",
    bio: "Hugo builds evaluation and observability platforms for teams bringing machine learning into production.",
  },
  {
    id: "lara-schmidt",
    name: "Lara Schmidt",
    title: "Site Reliability Engineer",
    company: "Harbor Cloud",
    bio: "Lara helps teams prepare for failure with simple reliability practices, useful signals, and calm incident response.",
  },
];

export const sessions: Session[] = [
  {
    id: "web-performance",
    title: "Performance by Default",
    description:
      "Learn a repeatable approach to finding the bottlenecks that shape real user experience. We will move from browser signals to practical rendering, loading, and caching decisions that teams can apply immediately.",
    speakerId: "maya-chen",
    startTime: "09:00",
    endTime: "09:45",
    room: "Atlas Hall",
    level: "intermediate",
    topics: ["Web"],
  },
  {
    id: "cloud-foundations",
    title: "Cloud Architecture Without the Maze",
    description:
      "A clear introduction to the building blocks of a reliable cloud system. Follow one service from request to deployment while learning which architecture decisions matter now and which can wait.",
    speakerId: "emre-kaya",
    startTime: "09:00",
    endTime: "09:45",
    room: "Bosporus Room",
    level: "beginner",
    topics: ["Cloud", "Backend"],
  },
  {
    id: "secure-by-design",
    title: "Threat Modeling for Busy Teams",
    description:
      "Turn security conversations into a lightweight team habit. This session uses a realistic product flow to identify assets, trust boundaries, likely threats, and fixes before code reaches production.",
    speakerId: "jonas-berg",
    startTime: "10:00",
    endTime: "10:45",
    room: "Atlas Hall",
    level: "intermediate",
    topics: ["Security"],
  },
  {
    id: "mobile-offline",
    title: "Offline-First Mobile That Feels Instant",
    description:
      "Design a mobile data layer that stays useful on unreliable networks. We will cover local state, synchronization, optimistic UI, and the product choices behind a trustworthy offline experience.",
    speakerId: "aisha-okafor",
    startTime: "10:00",
    endTime: "10:45",
    room: "Marmara Studio",
    level: "advanced",
    topics: ["Mobile", "Backend"],
  },
  {
    id: "ai-evaluation",
    title: "Evaluating AI Features Beyond the Demo",
    description:
      "Build a practical evaluation loop for AI-powered product features. Learn how to define success, assemble representative cases, inspect failure modes, and keep quality visible after launch.",
    speakerId: "hugo-lee",
    startTime: "11:00",
    endTime: "11:45",
    room: "Atlas Hall",
    level: "advanced",
    topics: ["AI", "DevOps"],
  },
  {
    id: "accessible-systems",
    title: "Accessibility as a System",
    description:
      "Move beyond one-off fixes by embedding accessible decisions in components, content, review, and testing. You will leave with a small operating model that works across product teams.",
    speakerId: "deniz-arslan",
    startTime: "11:00",
    endTime: "11:45",
    room: "Golden Horn",
    level: "beginner",
    topics: ["Web"],
  },
  {
    id: "event-driven",
    title: "Event-Driven Systems You Can Debug",
    description:
      "Event-driven architecture unlocks flexibility but can hide cause and effect. Explore message design, idempotency, tracing, and recovery patterns through a production-style order flow.",
    speakerId: "nora-patel",
    startTime: "13:00",
    endTime: "13:50",
    room: "Bosporus Room",
    level: "advanced",
    topics: ["Backend", "Cloud"],
  },
  {
    id: "useful-ai-apps",
    title: "From AI Prototype to Useful Product",
    description:
      "A product-minded guide to shaping AI ideas into dependable workflows. We will examine interaction design, boundaries, feedback, and the small decisions that separate a demo from a useful feature.",
    speakerId: "sofia-martins",
    startTime: "13:15",
    endTime: "14:00",
    room: "Atlas Hall",
    level: "beginner",
    topics: ["AI", "Web"],
  },
  {
    id: "delivery-pipelines",
    title: "A Delivery Pipeline Developers Trust",
    description:
      "Create fast, legible delivery pipelines with clear ownership and useful feedback. The session covers build stages, deployment confidence, rollback design, and sensible automation boundaries.",
    speakerId: "leo-garcia",
    startTime: "14:15",
    endTime: "15:00",
    room: "Golden Horn",
    level: "intermediate",
    topics: ["DevOps", "Cloud"],
  },
  {
    id: "modern-css",
    title: "Modern CSS, Fewer Workarounds",
    description:
      "Use today’s layout, container query, and cascade tools to replace brittle frontend patterns. We will refactor a realistic responsive interface and discuss progressive enhancement along the way.",
    speakerId: "deniz-arslan",
    startTime: "14:15",
    endTime: "15:00",
    room: "Marmara Studio",
    level: "intermediate",
    topics: ["Web"],
  },
  {
    id: "api-contracts",
    title: "API Contracts That Age Well",
    description:
      "Explore the naming, versioning, validation, and error conventions that keep APIs pleasant over time. Examples cover both early-stage services and larger multi-team environments.",
    speakerId: "nora-patel",
    startTime: "15:15",
    endTime: "16:00",
    room: "Bosporus Room",
    level: "intermediate",
    topics: ["Backend"],
  },
  {
    id: "incident-readiness",
    title: "Practice the Incident Before It Happens",
    description:
      "Reliability improves when teams rehearse. Learn to run a compact game day, choose a useful failure scenario, observe system behavior, and turn the findings into durable improvements.",
    speakerId: "lara-schmidt",
    startTime: "15:15",
    endTime: "16:00",
    room: "Atlas Hall",
    level: "intermediate",
    topics: ["DevOps", "Cloud"],
  },
  {
    id: "mobile-performance",
    title: "A Practical Mobile Performance Budget",
    description:
      "Translate speed into measurable budgets for startup, interaction, network, and battery use. Then connect those budgets to profiling and release decisions your whole team can understand.",
    speakerId: "aisha-okafor",
    startTime: "16:15",
    endTime: "17:00",
    room: "Marmara Studio",
    level: "intermediate",
    topics: ["Mobile"],
  },
  {
    id: "passkeys",
    title: "Passkeys in the Real World",
    description:
      "Understand how passkeys change sign-in flows and what product teams need to plan for. We will cover enrollment, recovery, device transitions, and rollout choices without skipping the awkward edges.",
    speakerId: "jonas-berg",
    startTime: "16:15",
    endTime: "17:00",
    room: "Golden Horn",
    level: "advanced",
    topics: ["Security", "Web"],
  },
];
